server:
  port: 8082
spring:
  application:
    name: mail_sender
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${spring.application.name}
  mail:
    host: smtp.163.com
    username: xiangshuai320@163.com
    password: X1angshua1
