spring:
  application:
    name: dataprocess
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${spring.application.name}
management:
  endpoints:
    web:
      exposure:
        include: '*'


